defaultPortal: Jeevan
portals:
  - name: Jeevan
    portalId: 39646145
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          --
        expiresAt: '2025-08-11T09:22:55.404Z'
    accountType: STANDARD
    personalAccessKey: >-
      
