trigger: none

# schedules:
#   - cron: "0 2 * * 6"  # Runs every Saturday at 2 AM UTC (Friday 9 PM EST)
#     displayName: " Theme Sync"
#     branches:
#       include:
#         - main
#     always: true

variables:
  HS_PAT: $(HUBSPOT_PERSONAL_ACCESS_KEY)

stages:
  - stage: SaveToThemeDev
    displayName: Save to `theme-dev` branch
    jobs:
      - job: FetchTheme
        displayName: Fetch theme and commit to theme-dev
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: none

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - powershell: |
              npm install -g @hubspot/cli

              # HubSpot Auth
              hs auth personalaccesskey "$env:HS_PAT"

              # Clone repo and checkout branch
              $repoUrl = "https://$(System.AccessToken)@$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)"
              git clone $repoUrl repo
              cd repo
              git checkout -b theme-dev 2>$null
              if ($LASTEXITCODE -ne 0) {
                  git checkout theme-dev
              }

              # Fetch theme from HubSpot
              hs fetch "DEV" ./themes/DEV

              git config user.name "AzureDevOps"
              git config user.email "devops@azure.com"
              git add .
              git commit -m "Automated sync for theme 'DEV' [theme-dev]"
              git push origin theme-dev
            env:
              HS_PAT: $(HUBSPOT_PERSONAL_ACCESS_KEY)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  # - stage: SaveToThemeTest
  #   displayName: Save to `theme-test` branch
  #   dependsOn: SaveToThemeDev
  #   jobs:
  #     - job: FetchTheme
  #       displayName: Fetch theme and commit to theme-test
  #       pool:
  #         vmImage: 'windows-latest'
  #       steps:
  #         - checkout: none
  #         - task: NodeTool@0
  #           inputs:
  #             versionSpec: '20.x'
  #           displayName: 'Install Node.js'

  #         - powershell: |
  #             npm install -g @hubspot/cli
  #             hs auth personalaccesskey --personal-access-key "$env:HS_PAT"

  #             git clone https://$(System.AccessToken)@dev.azure.com/$(System.CollectionUri.TrimEnd('/'))/$(System.TeamProject)/_git/$(Build.Repository.Name) repo
  #             cd repo
  #             git checkout -b theme-test || git checkout theme-test

  #             hs fetch "your-theme-name-test" ./themes/your-theme-name-test

  #             git config user.name "AzureDevOps"
  #             git config user.email "devops@azure.com"
  #             git add .
  #             git commit -m " automated sync for theme 'your-theme-name-test' [theme-test]"
  #             git push origin theme-test
  #           env:
  #             HS_PAT: $(HUBSPOT_PERSONAL_ACCESS_KEY)
  #             SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  # - stage: SaveToThemeStage
  #   displayName: Save to `theme-stage` branch
  #   dependsOn: SaveToThemeTest
  #   jobs:
  #     - job: FetchTheme
  #       displayName: Fetch theme and commit to theme-stage
  #       pool:
  #         vmImage: 'windows-latest'
  #       steps:
  #         - checkout: none
  #         - task: NodeTool@0
  #           inputs:
  #             versionSpec: '20.x'
  #           displayName: 'Install Node.js'

  #         - powershell: |
  #             npm install -g @hubspot/cli
  #             hs auth personalaccesskey --personal-access-key "$env:HS_PAT"

  #             git clone https://$(System.AccessToken)@dev.azure.com/$(System.CollectionUri.TrimEnd('/'))/$(System.TeamProject)/_git/$(Build.Repository.Name) repo
  #             cd repo
  #             git checkout -b theme-stage || git checkout theme-stage

  #             hs fetch "your-theme-name-stage" ./themes/your-theme-name-stage

  #             git config user.name "AzureDevOps"
  #             git config user.email "devops@azure.com"
  #             git add .
  #             git commit -m " automated sync for theme 'your-theme-name-stage' [theme-stage]"
  #             git push origin theme-stage
  #           env:
  #             HS_PAT: $(HUBSPOT_PERSONAL_ACCESS_KEY)
  #             SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  # - stage: SaveToThemeProd
  #   displayName: Save to `theme-prod` branch
  #   dependsOn: SaveToThemeStage
  #   jobs:
  #     - job: FetchTheme
  #       displayName: Fetch theme and commit to theme-prod
  #       pool:
  #         vmImage: 'windows-latest'
  #       steps:
  #         - checkout: none
  #         - task: NodeTool@0
  #           inputs:
  #             versionSpec: '20.x'
  #           displayName: 'Install Node.js'

  #         - powershell: |
  #             npm install -g @hubspot/cli
  #             hs auth personalaccesskey --personal-access-key "$env:HS_PAT"

  #             git clone https://$(System.AccessToken)@dev.azure.com/$(System.CollectionUri.TrimEnd('/'))/$(System.TeamProject)/_git/$(Build.Repository.Name) repo
  #             cd repo
  #             git checkout -b theme-prod || git checkout theme-prod

  #             hs fetch "your-theme-name-prod" ./themes/your-theme-name-prod

  #             git config user.name "AzureDevOps"
  #             git config user.email "devops@azure.com"
  #             git add .
  #             git commit -m " automated sync for theme 'your-theme-name-prod' [theme-prod]"
  #             git push origin theme-prod
  #           env:
  #             HS_PAT: $(HUBSPOT_PERSONAL_ACCESS_KEY)
  #             SYSTEM_ACCESSTOKEN: $(System.AccessToken)
