trigger: none

variables:
  HUBSPOT_PAT:       $(HUBSPOT_PERSONAL_ACCESS_KEY)
  HUBSPOT_PORTAL_ID: "39646145"
  REPO_URL:          "https://$(System.AccessToken)@grahamsio.visualstudio.com/CN%20Website/_git/Hubspot"

stages:
  - stage: SyncAllThemes
    displayName: Sync All HubSpot Themes
    jobs:
      - job: Sync
        pool:
          vmImage: 'windows-latest'
        steps:
          # 1) Get your repo locally
          - checkout: self

          # 2) Install Node.js
          - task: NodeTool@0
            displayName: Install Node.js 20.x
            inputs:
              versionSpec: '20.x'

          # 3) Fetch & push everything in one go
          - task: PowerShell@2
            displayName: Fetch & Push All Themes
            inputs:
              targetType: inline
              script: |
                # ensure hs can run
                npm install -g @hubspot/cli
                Install-Module powershell-yaml -Scope CurrentUser -Force -AllowClobber
                Import-Module powershell-yaml

                # themes to sync
                $themes = @('Code Ninja - Marketing Website','DEV','CN TEAM')
                $repoRoot = $env:BUILD_SOURCESDIRECTORY

                foreach ($themeName in $themes) {
                  Write-Host "`n=== Processing $themeName ==="

                  # slugify for branch & folder
                  $safe = $themeName.ToLower() `
                    -replace '[\/:*?"<>|]', '_' `
                    -replace '[^a-z0-9_]', '_' `
                    -replace '_+', '_'
                  $safe = $safe.Trim('_')
                  $branch = "theme_$safe"

                  # Prepare config
                  $cfgDir = Join-Path $env:USERPROFILE '.hubspotcli'
                  if (-not (Test-Path $cfgDir)) { New-Item -ItemType Directory -Path $cfgDir -Force > $null }
                  $cfgPath = Join-Path $cfgDir 'hubspot.config.yml'
                  @{
                    defaultPortal = $env:HUBSPOT_PORTAL_ID
                    portals       = @(@{
                      name              = $env:HUBSPOT_PORTAL_ID
                      portalId          = $env:HUBSPOT_PORTAL_ID
                      personalAccessKey = $env:HUBSPOT_PAT
                    })
                  } | ConvertTo-Yaml | Out-File $cfgPath -Encoding utf8 -Force
                  Start-Sleep 2

                  # Create folder in your repo
                  $dest = Join-Path $repoRoot "themes\$safe"
                  if (-not (Test-Path $dest)) { New-Item -ItemType Directory -Path $dest -Force > $null }

                  # Fetch directly into repo
                  hs fetch $themeName $dest --overwrite

                  # Git add/commit/push
                  Push-Location $repoRoot
                  git checkout -B $branch
                  git add "themes/$safe"
                  if (-not (git diff --cached --quiet)) {
                    git config user.name  'AutomatedBuild'
                    git config user.email 'build@yourdomain.com'
                    git commit -m "Sync HubSpot theme '$themeName' → $branch"
                    git push origin "HEAD:$branch"
                  } else {
                    Write-Host "No changes for '$themeName'."
                  }
                  Pop-Location
                }
            env:
              HUBSPOT_PAT:        $(HUBSPOT_PAT)
              HUBSPOT_PORTAL_ID:  $(HUBSPOT_PORTAL_ID)
              System.AccessToken: $(System.AccessToken)
