trigger: none

variables:
  HUBSPOT_PAT:       $(HUBSPOT_PERSONAL_ACCESS_KEY)
  HUBSPOT_PORTAL_ID: "39646145"
  REPO_URL:          "https://$(System.AccessToken)@grahamsio.visualstudio.com/CN%20Website/_git/Hubspot"
  WORKDIR:           "$(Agent.TempDirectory)\repo"

stages:
  - stage: SyncAllThemes
    displayName: Sync All HubSpot Themes
    jobs:
      - job: Sync
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: none

          - task: NodeTool@0
            displayName: Install Node.js 20.x
            inputs:
              versionSpec: '20.x'

          - task: PowerShell@2
            displayName: Fetch & Push All Themes
            inputs:
              targetType: inline
              script: |
                Install-Module powershell-yaml -Scope CurrentUser -Force -AllowClobber
                Import-Module powershell-yaml
                $WORKDIR = Join-Path $env:BUILD_SOURCESDIRECTORY 'temp-repo'

                $themes = @(
                  'Code Ninja - Marketing Website',
                  'DEV',
                  'CN TEAM'
                )

                foreach ($themeName in $themes) {
                  Write-Host "`n--- Processing $themeName ---"

                  $safeName = $themeName.ToLower() -replace '[^a-z0-9]', '-' -replace '-+', '-'
                  $safeName = $safeName.Trim('-')
                  $branchName = "theme-$safeName"

                  # Generate safe folder name with underscores
                  $folderSafeName = $themeName -replace '[\/:*?"<>|]', '_' -replace '\s+', '_' -replace '_+', '_'

                  # Clean and clone fresh
                  if (Test-Path $WORKDIR) {
                    Set-Location $env:TEMP
                    Remove-Item -Recurse -Force $WORKDIR
                  }
                  git clone $env:REPO_URL $WORKDIR
                  Push-Location $WORKDIR

                  git checkout -B $branchName

                  # Setup HubSpot CLI
                  npm install -g @hubspot/cli
                  Write-Host "Installed HubSpot CLI"
                  $cfgDir = Join-Path $env:USERPROFILE '.hubspotcli'
                  if (-not (Test-Path $cfgDir)) {
                    New-Item -ItemType Directory -Path $cfgDir -Force > $null
                  }
                  $cfgPath = Join-Path $cfgDir 'hubspot.config.yml'
                  $cfg = @{
                    defaultPortal = $env:HUBSPOT_PORTAL_ID
                    portals       = @(@{
                      name               = $env:HUBSPOT_PORTAL_ID
                      portalId           = $env:HUBSPOT_PORTAL_ID
                      personalAccessKey  = $env:HUBSPOT_PAT
                    })
                  }
                  $cfg | ConvertTo-Yaml | Out-File $cfgPath -Encoding utf8 -Force
                  Start-Sleep -Seconds 2

                  # Fetch the theme
                  $themesDir = Join-Path $WORKDIR "themes"
                  $dest = Join-Path $themesDir $folderSafeName
                  $parent = Split-Path -Path $dest -Parent
                  if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force > $null }

                  hs fetch "$themeName" "$dest" --overwrite
                  if (-not (Test-Path $dest)) {
                    Write-Error "Fetch failed or theme '$themeName' not found at $dest. Skipping."
                    Pop-Location
                    continue
                  }

                  # Commit and push
                  git add "themes\$folderSafeName"
                  if (-not (git diff --cached --quiet)) {
                    git config user.name  'AutomatedBuild'
                    git config user.email 'build@yourdomain.com'
                    git commit -m "Sync HubSpot theme '$themeName' → $branchName"
                    git push origin "HEAD:$branchName"
                  } else {
                    Write-Host "No changes for '$themeName'."
                  }

                  Pop-Location
                }
            env:
              HUBSPOT_PAT:        $(HUBSPOT_PAT)
              HUBSPOT_PORTAL_ID:  $(HUBSPOT_PORTAL_ID)
              REPO_URL:           $(REPO_URL)
              WORKDIR:            $(WORKDIR)
              System_AccessToken: $(System.AccessToken)
